# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 02:19
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u7c7b\u522b\u540d\u79f0')),
                ('path', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('display_order', models.SmallIntegerField(default=0, verbose_name='\u663e\u793a\u6392\u5e8f')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Category', verbose_name='\u4e0a\u7ea7\u5206\u7c7b')),
            ],
            options={
                'ordering': ['path'],
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5546\u54c1\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='\u5e10\u53f7')),
                ('realname', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='\u624b\u673a')),
                ('password', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='upload/avatar/%Y/%m/%d/', verbose_name='\u5934\u50cf')),
                ('sex', models.SmallIntegerField(choices=[(0, '\u5973'), (1, '\u7537'), (2, '\u672a\u77e5')], default='2', verbose_name='\u6027\u522b')),
                ('point', models.IntegerField(default=0, verbose_name='\u79ef\u5206')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6536\u4ef6\u5730\u5740')),
                ('register_at', models.DateField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('status', models.SmallIntegerField(default=1, verbose_name='\u72b6\u6001')),
            ],
            options={
                'ordering': ('register_at',),
                'verbose_name': '\u5ba2\u6237',
                'verbose_name_plural': '\u5ba2\u6237\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='CustomerConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=10)),
                ('openid', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='connect', to='shop.Customer', verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPointLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=15, verbose_name='\u4e8b\u4ef6')),
                ('opertion', models.CharField(choices=[('+', '\u589e\u52a0'), ('-', '\u51cf\u53bb')], default='+', max_length=1, verbose_name='\u64cd\u4f5c\u7c7b\u578b')),
                ('score', models.IntegerField(verbose_name='\u5206\u503c')),
                ('create_at', models.DateField(verbose_name='\u53d1\u751f\u65f6\u95f4')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_log_owner', to='shop.Customer', verbose_name='\u6240\u5c5e\u5ba2\u6237')),
                ('opertor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_log_oper', to='shop.Customer', verbose_name='\u8d21\u732e\u8005')),
            ],
            options={
                'ordering': ('create_at',),
                'verbose_name': '\u79ef\u5206\u8bb0\u5f55',
                'verbose_name_plural': '\u79ef\u5206\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='CustomerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(verbose_name='\u7ea7\u522b')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer', verbose_name='\u5ba2\u6237')),
                ('upper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper', to='shop.Customer', verbose_name='\u4e0a\u7ea7\u5ba2\u6237')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u5173\u7cfb',
                'verbose_name_plural': '\u5ba2\u6237\u5173\u7cfb',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5c5e\u6027\u540d\u79f0')),
                ('display_order', models.IntegerField(verbose_name='\u663e\u793a\u6392\u5e8f')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='\u5546\u54c1\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u5c5e\u6027',
                'verbose_name_plural': '\u5546\u54c1\u5c5e\u6027',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='\u63d0\u95ee\u65f6\u95f4')),
                ('question_text', models.TextField(verbose_name='\u63d0\u95ee\u5185\u5bb9')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='\u7b54\u590d\u5185\u5bb9')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer', verbose_name='\u5ba2\u6237')),
            ],
            options={
                'ordering': ('create_at',),
                'verbose_name': '\u54a8\u8be2',
                'verbose_name_plural': '\u5ba2\u6237\u54a8\u8be2',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u5185\u5bb9')),
                ('type', models.CharField(choices=[('global', '\u9996\u9875\u5e7b\u706f\u7247'), ('news', '\u5b9e\u65f6\u516c\u544a')], default='news', max_length=10, verbose_name='\u7c7b\u578b')),
                ('cover', models.ImageField(blank=True, help_text='\u56fe\u7247\u5c3a\u5bf8\u6bd4\u4f8b\u4e3a2:1(\u957f\u5bbd)', null=True, upload_to='upload/notice/%Y/%m/%d/', verbose_name='\u56fe\u7247')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('public_at', models.DateField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('status', models.SmallIntegerField(choices=[(0, '\u8349\u7a3f'), (1, '\u53d1\u5e03')], default=1, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u516c\u544a',
                'verbose_name_plural': '\u4fc3\u9500\u516c\u544a',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u603b\u4ef7')),
                ('realname', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6536\u4ef6\u4eba')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6536\u4ef6\u5730\u5740')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9644\u8a00')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('status', models.SmallIntegerField(choices=[(0, '\u5df2\u521b\u5efa'), (1, '\u5df2\u4e0b\u5355'), (2, '\u672a\u652f\u4ed8'), (3, '\u5df2\u4ed8\u6b3e'), (4, '\u5f85\u5ba1\u6838'), (5, '\u5df2\u5ba1\u6838'), (6, '\u5df2\u53d1\u8d27'), (7, '\u5df2\u6d88\u8d39'), (8, '\u5df2\u5b8c\u6210')], default=0, verbose_name='\u72b6\u6001')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Customer', verbose_name='\u5ba2\u6237')),
            ],
            options={
                'ordering': ('create_at', 'status'),
                'verbose_name': '\u8ba2\u5355',
                'verbose_name_plural': '\u5ba2\u6237\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('count', models.SmallIntegerField(default=1, verbose_name='\u6570\u91cf')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='\u4ef7\u683c')),
                ('status', models.SmallIntegerField(choices=[(0, '\u672a\u6d88\u8d39'), (1, '\u5df2\u6d88\u8d39')], default=0, verbose_name='\u72b6\u6001')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in', to='shop.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='\u5546\u54c1SKU')),
                ('name', models.CharField(max_length=50, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('description', models.TextField(verbose_name='\u5546\u54c1\u7b80\u4ecb')),
                ('type', models.CharField(choices=[('G', '\u4ea7\u54c1'), ('S', '\u9879\u76ee')], default='G', max_length=1, verbose_name='\u5546\u54c1\u7c7b\u578b')),
                ('recommend', models.SmallIntegerField(choices=[(0, '\u5426'), (1, '\u662f')], default=0, verbose_name='\u9996\u9875\u63a8\u8350')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('stock', models.IntegerField(default=0, verbose_name='\u5e93\u5b58\u6570\u91cf')),
                ('point', models.IntegerField(default=0, verbose_name='\u79ef\u5206\u5956\u52b1')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u4ea7\u54c1\u8be6\u60c5')),
                ('cover', models.ImageField(help_text='\u56fe\u7247\u5c3a\u5bf8\u6bd4\u4f8b\u4e3a4:3(\u957f\u5bbd)', null=True, upload_to='upload/products/%Y/%m/%d/', verbose_name='\u5c01\u9762\u56fe\u7247')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('open_at', models.DateField(default=datetime.date(2016, 1, 9), verbose_name='\u4e0a\u67b6\u65f6\u95f4')),
                ('close_at', models.DateField(blank=True, null=True, verbose_name='\u4e0b\u67b6\u65f6\u95f4')),
                ('status', models.SmallIntegerField(choices=[(0, '\u5f85\u4e0a\u67b6'), (1, '\u5df2\u4e0a\u67b6'), (2, '\u5df2\u4e0b\u67b6'), (3, '\u552e\u7f44')], default=0, verbose_name='\u72b6\u6001')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='\u5546\u54c1\u5206\u7c7b')),
            ],
            options={
                'ordering': ('open_at', 'status'),
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='\u503c')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item', verbose_name='\u5b57\u6bb5')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.Product', verbose_name='\u5546\u54c1')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u5c5e\u6027',
                'verbose_name_plural': '\u4ea7\u54c1\u5c5e\u6027',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='\u5b57\u6bb5')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bf4\u660e')),
                ('values', models.TextField(verbose_name='\u503c')),
            ],
            options={
                'verbose_name': '\u8bbe\u7f6e',
                'verbose_name_plural': '\u7ad9\u70b9\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Shopcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='\u603b\u4ef7')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer', verbose_name='\u5ba2\u6237')),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66',
                'verbose_name_plural': '\u8d2d\u7269\u8f66',
            },
        ),
        migrations.CreateModel(
            name='ShopcartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('count', models.SmallIntegerField(default=1, verbose_name='\u6570\u91cf')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='\u4ef7\u683c')),
                ('checked', models.BooleanField(default=True, verbose_name='\u9009\u62e9')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('shopcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in', to='shop.Shopcart')),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66',
                'verbose_name_plural': '\u8d2d\u7269\u8f66',
            },
        ),
        migrations.AddField(
            model_name='shopcart',
            name='products',
            field=models.ManyToManyField(through='shop.ShopcartProduct', to='shop.Product', verbose_name='\u5546\u54c1\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='shop.OrderProduct', to='shop.Product', verbose_name='\u5546\u54c1\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='item',
            name='products',
            field=models.ManyToManyField(through='shop.ProductItem', to='shop.Product'),
        ),
        migrations.AlterIndexTogether(
            name='customer',
            index_together=set([('username', 'phone')]),
        ),
    ]
