# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u7c7b\u522b\u540d\u79f0')),
                ('display_order', models.SmallIntegerField(verbose_name='\u663e\u793a\u6392\u5e8f')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Category', verbose_name='\u4e0a\u7ea7\u5206\u7c7b')),
            ],
            options={
                'ordering': ('display_order',),
                'verbose_name': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='\u5e10\u53f7')),
                ('realname', models.CharField(max_length=15, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(max_length=15, verbose_name='\u624b\u673a')),
                ('password', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
                ('avatar', models.FileField(upload_to='upload/products/%Y/%m/%d/', verbose_name='\u5934\u50cf')),
                ('sex', models.SmallIntegerField(choices=[('0', '\u5973'), ('1', '\u7537'), ('2', '\u672a\u77e5')], default='2', verbose_name='\u6027\u522b')),
                ('point', models.IntegerField(verbose_name='\u79ef\u5206')),
                ('address', models.CharField(max_length=255, verbose_name='\u6536\u4ef6\u5730\u5740')),
                ('register_at', models.DateField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
            ],
            options={
                'ordering': ('register_at',),
                'verbose_name': '\u5ba2\u6237',
            },
        ),
        migrations.CreateModel(
            name='CustomerConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=10)),
                ('openid', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='connect', to='shop.Customer', verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPointLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=15, verbose_name='\u4e8b\u4ef6')),
                ('opertion', models.CharField(choices=[('+', '\u589e\u52a0'), ('-', '\u51cf\u53bb')], default='+', max_length=1, verbose_name='\u64cd\u4f5c\u7c7b\u578b')),
                ('score', models.IntegerField(verbose_name='\u5206\u503c')),
                ('create_at', models.DateField(verbose_name='\u53d1\u751f\u65f6\u95f4')),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='point_log_owner', to='shop.Customer', verbose_name='\u6240\u5c5e\u5ba2\u6237')),
                ('opertor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='point_log_oper', to='shop.Customer', verbose_name='\u8d21\u732e\u8005')),
            ],
            options={
                'ordering': ('create_at',),
                'verbose_name': '\u79ef\u5206\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='CustomerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(verbose_name='\u7ea7\u522b')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='shop.Customer', verbose_name='\u5ba2\u6237')),
                ('upper', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='upper', to='shop.Customer', verbose_name='\u4e0a\u7ea7\u5ba2\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='\u59d3\u540d')),
                ('description', models.CharField(max_length=255, verbose_name='\u7b80\u4ecb')),
            ],
            options={
                'verbose_name': '\u533b\u751f',
            },
        ),
        migrations.CreateModel(
            name='DoctorDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_at', models.DateTimeField(verbose_name='\u503c\u73ed\u65f6\u95f4')),
                ('status', models.SmallIntegerField(choices=[(1, '\u6b63\u5e38\u503c\u73ed'), (0, '\u7f3a\u52e4')], default=1, verbose_name='\u72b6\u6001')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Doctor', verbose_name='\u533b\u751f')),
            ],
            options={
                'verbose_name': '\u503c\u73ed',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5c5e\u6027\u540d\u79f0')),
                ('display_order', models.IntegerField(verbose_name='\u663e\u793a\u6392\u5e8f')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('type', models.CharField(max_length=10, verbose_name='\u7c7b\u578b')),
                ('create_at', models.DateField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('public_at', models.DateField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('status', models.SmallIntegerField(choices=[(1, '\u53d1\u5e03'), (0, '\u8349\u7a3f')], default=1, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u516c\u544a',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.TextField(verbose_name='\u5546\u54c1\u4fe1\u606f')),
                ('total_price', models.FloatField(verbose_name='\u603b\u4ef7')),
                ('type', models.CharField(choices=[('G', '\u4ea7\u54c1'), ('S', '\u9879\u76ee')], editable=False, max_length=1, verbose_name='\u7c7b\u578b')),
                ('booking_at', models.DateField(verbose_name='\u9884\u7ea6\u65f6\u95f4')),
                ('address', models.CharField(max_length=255, verbose_name='\u6536\u4ef6\u5730\u5740')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('status', models.SmallIntegerField(choices=[(0, '\u672a\u4e0b\u5355'), (1, '\u5df2\u4e0b\u5355'), (2, '\u672a\u652f\u4ed8'), (3, '\u5df2\u4ed8\u6b3e'), (4, '\u5f85\u5ba1\u6838'), (5, '\u5df2\u5ba1\u6838'), (6, '\u5df2\u53d1\u8d27'), (7, '\u5df2\u6d88\u8d39'), (8, '\u5df2\u5b8c\u6210')], default=0, verbose_name='\u72b6\u6001')),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='shop.Customer', verbose_name='\u5ba2\u6237')),
            ],
            options={
                'ordering': ('create_at', 'status'),
                'verbose_name': '\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='\u5546\u54c1\u5e8f\u53f7')),
                ('name', models.CharField(max_length=50, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('description', models.TextField(verbose_name='\u5546\u54c1\u7b80\u4ecb')),
                ('type', models.CharField(choices=[('G', '\u4ea7\u54c1'), ('S', '\u9879\u76ee')], default='G', max_length=1, verbose_name='\u5546\u54c1\u7c7b\u578b')),
                ('price', models.FloatField(verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('stock', models.IntegerField(verbose_name='\u5e93\u5b58\u6570\u91cf')),
                ('content', models.TextField(verbose_name='\u4ea7\u54c1\u8be6\u60c5')),
                ('image1', models.FileField(upload_to='upload/products/%Y/%m/%d/', verbose_name='\u4ea7\u54c1\u56fe\u72471')),
                ('image2', models.FileField(upload_to='upload/products/%Y/%m/%d/', verbose_name='\u4ea7\u54c1\u56fe\u72472')),
                ('image3', models.FileField(upload_to='upload/products/%Y/%m/%d/', verbose_name='\u4ea7\u54c1\u56fe\u72473')),
                ('image4', models.FileField(upload_to='upload/products/%Y/%m/%d/', verbose_name='\u4ea7\u54c1\u56fe\u72474')),
                ('image5', models.FileField(upload_to='upload/products/%Y/%m/%d/', verbose_name='\u4ea7\u54c1\u56fe\u72475')),
                ('image6', models.FileField(upload_to='upload/products/%Y/%m/%d/', verbose_name='\u4ea7\u54c1\u56fe\u72476')),
                ('image7', models.FileField(upload_to='upload/products/%Y/%m/%d/', verbose_name='\u4ea7\u54c1\u56fe\u72477')),
                ('image8', models.FileField(upload_to='upload/products/%Y/%m/%d/', verbose_name='\u4ea7\u54c1\u56fe\u72478')),
                ('image9', models.FileField(upload_to='upload/products/%Y/%m/%d/', verbose_name='\u4ea7\u54c1\u56fe\u72479')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('open_at', models.DateField(verbose_name='\u4e0a\u67b6\u65f6\u95f4')),
                ('close_at', models.DateField(verbose_name='\u4e0b\u67b6\u65f6\u95f4')),
                ('status', models.SmallIntegerField(choices=[(0, '\u5f85\u4e0a\u67b6'), (1, '\u5df2\u4e0a\u67b6'), (2, '\u5df2\u4e0b\u67b6'), (3, '\u552e\u7f44')], default=0, verbose_name='\u72b6\u6001')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
            options={
                'ordering': ('open_at', 'status'),
                'verbose_name': '\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='\u5b57\u6bb5')),
                ('values', models.TextField(verbose_name='\u503c')),
            ],
            options={
                'verbose_name': '\u8bbe\u7f6e',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='products',
            field=models.ManyToManyField(through='shop.ProductItem', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='\u9879\u76ee'),
        ),
    ]
