# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9644\u8a00'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='order',
            name='realname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6536\u4ef6\u4eba'),
        ),
        migrations.AlterField(
            model_name='product',
            name='open_at',
            field=models.DateField(default=datetime.date(2016, 1, 7), verbose_name='\u4e0a\u67b6\u65f6\u95f4'),
        ),
    ]
