# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 04:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('count', models.SmallIntegerField(verbose_name='\u6570\u91cf')),
                ('total', models.FloatField(verbose_name='\u603b\u4ef7')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AlterField(
            model_name='product',
            name='close_at',
            field=models.DateField(blank=True, null=True, verbose_name='\u4e0b\u67b6\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='open_at',
            field=models.DateField(default=datetime.date(2016, 1, 3), verbose_name='\u4e0a\u67b6\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='shop.OrderProduct', to='shop.Product', verbose_name='\u5546\u54c1\u4fe1\u606f'),
        ),
    ]
