# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160107_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='\u63d0\u95ee\u65f6\u95f4')),
                ('question_text', models.TextField(verbose_name='\u63d0\u95ee\u5185\u5bb9')),
                ('answer_text', models.TextField(verbose_name='\u7b54\u590d\u5185\u5bb9')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer')),
            ],
        ),
    ]
