# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20160103_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='count',
            field=models.SmallIntegerField(default=1, verbose_name='\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='joined_at',
            field=models.DateField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='total_price',
            field=models.FloatField(default=0.0, verbose_name='\u603b\u4ef7'),
        ),
        migrations.AlterField(
            model_name='shopcartproduct',
            name='count',
            field=models.SmallIntegerField(default=1, verbose_name='\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='shopcartproduct',
            name='joined_at',
            field=models.DateField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='shopcartproduct',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='\u4ef7\u683c'),
        ),
    ]
